"""SQLite persistence layer (see planning/TEAM.md for the contract)."""

from .connection import DEFAULT_USER, connect, get_db_path, now_iso, transaction
from .queries import (
    Position,
    add_to_watchlist,
    delete_position,
    downsample,
    get_cash,
    get_history,
    get_position,
    insert_chat_message,
    insert_snapshot,
    insert_trade,
    is_on_watchlist,
    last_trade_prices,
    list_positions,
    list_watchlist,
    recent_chat_messages,
    remove_from_watchlist,
    set_cash,
    tracked_tickers,
    upsert_position,
)
from .schema import DEFAULT_CASH, DEFAULT_WATCHLIST, init_db

__all__ = [
    "DEFAULT_CASH",
    "DEFAULT_USER",
    "DEFAULT_WATCHLIST",
    "Position",
    "add_to_watchlist",
    "connect",
    "delete_position",
    "downsample",
    "get_cash",
    "get_db_path",
    "get_history",
    "get_position",
    "init_db",
    "insert_chat_message",
    "insert_snapshot",
    "insert_trade",
    "is_on_watchlist",
    "last_trade_prices",
    "list_positions",
    "list_watchlist",
    "now_iso",
    "recent_chat_messages",
    "remove_from_watchlist",
    "set_cash",
    "tracked_tickers",
    "transaction",
    "upsert_position",
]
